version: '3'
services:
  test-db:
    image: "postgres"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
          - 5474:5432
    volumes:
      - test-data:/var/lib/postgresql/data

  dev-db:
    image: "postgres"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
          - 5464:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  prod-db:
    image: "postgres"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
          - 5484:5432
    volumes:
      - prod-data:/var/lib/postgresql/data


  prod-app:
    build: ./Dockerfile.production


volumes:
  db-data:
  test-data:

